### ISSUE TITLE
App crashing when swiping away

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#80]
Process: org.fraunhofer.cese.madcap, PID: 32246
                                                   java.lang.RuntimeException: Unable to stop service org.fraunhofer.cese.madcap.services.DataCollectionService@61359ff: java.util.ConcurrentModificationException
                                                       at android.app.ActivityThread.handleStopService(ActivityThread.java:3344)
                                                       at android.app.ActivityThread.-wrap27(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.util.ConcurrentModificationException
                                                       at java.util.ArrayList$Itr.next(ArrayList.java:831)
                                                       at org.fraunhofer.cese.madcap.services.DataCollectionService.disableAllListeners(DataCollectionService.java:193)
                                                       at org.fraunhofer.cese.madcap.services.DataCollectionService.onDestroy(DataCollectionService.java:134)
                                                       at android.app.ActivityThread.handleStopService(ActivityThread.java:3327)
                                                       at android.app.ActivityThread.-wrap27(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by llayman** [comment]
This error is very strange. You only get these exceptions when two threads are trying to modify a non-thread safe Collection at the same time. Why is onDestroy() being called twice I wonder...

**Comment by mmueller301** [comment]
@llayman the old madcap app instanciated all probes one by one and not in a list. Maybe there was a reason for this?

**Comment by llayman** [comment]
@mmueller301 I do not know if there was a reason.

**Comment by mmueller301** [comment]
We should make the list really thread safe with applying both methods described here: https://techvivek.wordpress.com/2009/08/29/difference-between-arraylist-and-copyonwritearraylist/
