### ISSUE TITLE
onBoot bug

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#97]
Autostart is not working anymore.

**Comment by llayman** [comment]
```
12-02 10:44:25.779 10953-11110/org.fraunhofer.cese.madcap E/AndroidRuntime: FATAL EXCEPTION: IntentService[OnBootService]
                                                                            Process: org.fraunhofer.cese.madcap, PID: 10953
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.auth.api.signin.GoogleSignInAccount org.fraunhofer.cese.madcap.authentication.MadcapAuthManager.getUser()' on a null object reference
                                                                                at org.fraunhofer.cese.madcap.boot.OnBootService.onHandleIntent(OnBootService.java:52)
                                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
```
